version: '2'
services:


  fund-service:
    build: fund-service
    command: /bin/bash -c "wait-for-it -t 0 localhost:3306 && /app/start /app/fund-service-latest.jar"
    mem_limit: 384M
    network_mode: "host"
    ports:
      - 10010:10010
    environment:
      SPRING_PROFILES_ACTIVE: dev

  inventory-service:
    build: inventory-service
    command: /bin/bash -c "wait-for-it -t 0 localhost:3306 && /app/start /app/inventory-service-latest.jar"
    mem_limit: 384M
    network_mode: "host"
    ports:
      - 10011:10011
    environment:
      SPRING_PROFILES_ACTIVE: dev
 
  invest-service:
    build: invest-service
    command: /bin/bash -c "wait-for-it -t 0 localhost:3306 && /app/start /app/invest-service-latest.jar"
    mem_limit: 384M
    network_mode: "host"
    ports:
      - 10012:10012
    environment:
      SPRING_PROFILES_ACTIVE: dev

  trade-service:
    build: trade-service
    command: /bin/bash -c "wait-for-it -t 0 localhost:3306 && /app/start /app/trade-service-latest.jar"
    mem_limit: 384M
    network_mode: "host"
    ports:
      - 10013:10013
    environment:
      SPRING_PROFILES_ACTIVE: dev

  web-gateway:
    build: web-ui/web-gateway
    mem_limit: 384M
    network_mode: "host"
    ports:
      - 8088:8088
    environment:
      SPRING_PROFILES_ACTIVE: dev

  general-service:
    build: general-service
    command: /bin/bash -c "wait-for-it -t 0 localhost:6379 && /app/start /app/general-service-latest.jar"
    mem_limit: 384M
    network_mode: "host"
    ports:
      - 10014:10014
    environment:
      SPRING_PROFILES_ACTIVE: dev
  
  trading-office-service:
    build: trading-office-service
    command: /bin/bash -c "wait-for-it -t 0 localhost:6379 && /app/start /app/trading-office-service-latest.jar"
    mem_limit: 384M
    network_mode: "host"
    ports:
      - 10015:10015
    environment:
      SPRING_PROFILES_ACTIVE: dev    
      
