version: '2'
services:


  fund-service:
    build: fund-service
    command: /bin/bash -c "wait-for-it -t 0 localhost:3306 && /app/start /app/fund-service-latest.jar"
    network_mode: "host"
    ports:
      - 10010:10010
    environment:
      SPRING_PROFILES_ACTIVE: dev

  inventory-service:
    build: inventory-service
    command: /bin/bash -c "wait-for-it -t 0 localhost:3306 && /app/start /app/inventory-service-latest.jar"
    network_mode: "host"
    ports:
      - 10011:10011
    environment:
      SPRING_PROFILES_ACTIVE: dev
 
  invest-service:
    build: invest-service
    command: /bin/bash -c "wait-for-it -t 0 localhost:3306 && /app/start /app/invest-service-latest.jar"
    network_mode: "host"
    ports:
      - 10012:10012
    environment:
      SPRING_PROFILES_ACTIVE: dev

  trade-service:
    build: trade-service
    command: /bin/bash -c "wait-for-it -t 0 localhost:3306 && /app/start /app/trade-service-latest.jar"
    network_mode: "host"
    ports:
      - 10013:10013
    environment:
      SPRING_PROFILES_ACTIVE: dev

  web-gateway:
    build: web-ui/web-gateway
    network_mode: "host"
    ports:
      - 8088:8088
    environment:
      SPRING_PROFILES_ACTIVE: dev

  sequence-service:
    build: sequence-service
    container_name: sequence-service
    network_mode: "host"
    ports:
      - 10200:10200
    environment:
      SPRING_PROFILES_ACTIVE: dev
