app:
  version: "%%VERSION%%"
  
server:
  port: 10012

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
  redis:
    database: 2
    password:    
    pool: 
      max-idle: 8 
      min-idle: 0 
      max-active: 8 
      max-wait: -1 
  kafka:
    consumer:
      group-id: invest-service  
    producer:
      key-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

eureka:
  instance:
    preferIpAddress: true
  client:
    registryFetchIntervalSeconds: 5
    instanceInfoReplicationIntervalSeconds: 5
    initialInstanceInfoReplicationIntervalSeconds: 5

management:
  security:
    enabled: false
    
kafka:
  stream:
    appid: invest-service-kafka-stream

---

spring:
  profiles: dev
  datasource:
    url: jdbc:mysql://localhost:3306/investdb?characterEncoding=utf-8
    username: mariadb
    password: mariadb
  kafka:
    bootstrap-servers: localhost:9092
  redis: 
    host: localhost
    port: 6379 
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:10100/eureka/
kafka:
  broker:
    host: localhost:9092
  zookeeper:
    host: localhost:2181
---

spring:
  profiles: prod
  datasource:
    url: jdbc:mysql://mariadb:3308/investdb?characterEncoding=utf-8

eureka:
  client:
    serviceUrl:
      defaultZone: http://discoery-service:10100/eureka/
